Development
HorizenLabs/eon-explorer pull request #30
Opened 2023-10-23 11:05 UTC by davehorizen

3.1.1 from development branch:

- Reorg blocks page fix

2023-10-23 11:24 UTC, otoumas requested changes
If a new release will be created please update also the version here: https://github.com/HorizenLabs/eon-explorer/blob/eef3a3801e991dd75fd6dc7105fcf0f67e3d0c85/mix.exs#L10
Check other possible places where version might require upgrade

2023-10-23 13:06 UTC, davehorizen commented
> If a new release will be created please update also the version here:
> 
> https://github.com/HorizenLabs/eon-explorer/blob/eef3a3801e991dd75fd6dc7105fcf0f67e3d0c85/mix.exs#L10
> 
> 
> Check other possible places where version might require upgrade

Right! [PR opened](https://github.com/HorizenLabs/eon-explorer/pull/31) to update version to 3.1.1
The version seems to be reported only in the elixir script `mix` file

2023-10-24 09:46 UTC, otoumas approved these changes
LGTM

2023-10-24 12:04 UTC, rabyyuson approved these changes

2023-10-24 12:56 UTC, merged